version: "3"

services:
  postgresdb:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: demo
    networks: 
    - demo-network

  keycloak:
    image: jboss/keycloak:15.0.2
    ports:
    - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres # tell keycloak use postgres as db
      DB_ADDR: postgresdb # postdb instance name
      DB_USER: keycloak
      DB_PASSWORD: demo
    depends_on:
        - postgresdb
    networks: 
    - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  postgresdata: